spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundoo
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: csandhyait@gmail.com
    password: 212915205036
    port: 587
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enable: true

  elasticsearch:
    clustername: fundoonotes
    host: localhost
    port: 9200

  #  rabbitmq:
  #    host: localhost
  #      username: test
  #      password: test
  #      port: 5672
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  main:
    allow:
      bean:
        definition:
          overriding: true